//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace coursedesign.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class engineering
    {
        public Nullable<System.DateTime> birth { get; set; }
        public int sex { get; set; }
        public string name { get; set; }
        public int id { get; set; }
        public string place { get; set; }
        public Nullable<int> education { get; set; }
        public string address { get; set; }
        public string telephone { get; set; }
        public string workage { get; set; }
        public Nullable<int> salary { get; set; }
    }
}
