//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace coursedesign
{
    using System;
    using System.Collections.Generic;
    
    public partial class engineering
    {
        public Nullable<System.DateTime> birth { get; set; }
        public int sex { get; set; }
        public string name { get; set; }
        public int id { get; set; }
        public string place { get; set; }
        public Nullable<int> education { get; set; }
        public string address { get; set; }
        public string telephone { get; set; }
        public string workage { get; set; }
        public Nullable<int> salary { get; set; }
        public void SetValue(engineering e, engineering model)
        {
            e.id = model.id;
            e.name = model.name.Trim();
            e.place = model.place.Trim();
            e.salary = model.salary;
            e.sex = model.sex;
            e.telephone = model.telephone.Trim();
            e.workage = model.workage.Trim();
            e.address = model.address.Trim();
            e.education = model.education;
            e.birth = model.birth;
        }
    }
}
